### ISSUE TITLE
Unbuildable

### ISSUE THREAD

**Issue by Ygarr** [WebicityBrowser/Webicity-Java#7]
Is it buildable yet? (

**Comment by JasonTheKitten** [comment]
Hello!
The default branch is not in a buildable state right now, but the "ribbon" branch is
Please check out the "ribbon" branch for now (`git checkout -b ribbon`)
(also make sure that you are using jdk 17)
I was rewriting the browser, but then took a multi-month break (sorry)
I've gone back to working on it, but haven't pushed anything yet.

Please note that this project is also still under development, so it is not usable for daily use yet.

**Comment by Ygarr** [comment]
Thanks a lot

**Comment by JasonTheKitten** [comment]
The current branch is almost caught up to the Ribbon branch. I will just close this issue when it is caught up.

ShadowJar support is also broken at the moment, so shaded jars will crash (noclassdef: com.sun.util.Cleaner (in Skija dependency). Modern Java versions use java.lang.ref.Cleaner, so I tried relocating the class, but it resulted in a broken class file so that did not work out either).

Continue to note that this project is under construction, so it is not very usable yet.

**Comment by JasonTheKitten** [comment]
ShadowJar support has been fixed.

Continue to note that this project is under (very slow and sparce) construction, so it is not very usable yet.
